/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Report whether the HTTP process is alive */
        get: operations["getLiveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Report whether the database, data root, and worker are usable */
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Report only capabilities currently implemented */
        get: operations["getCapabilities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stage a document and create a durable asynchronous conversion */
        post: operations["createConversion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Poll one durable conversion */
        get: operations["getConversion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversions/{id}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List atomically published artifacts */
        get: operations["listConversionArtifacts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversions/{id}/artifacts/markdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream the published Markdown artifact */
        get: operations["downloadConversionMarkdown"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversions/{id}/artifacts/manifest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream the published provenance manifest */
        get: operations["downloadConversionManifest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            status: string;
            /** @constant */
            service: "tool-kit-converter";
            serviceVersion: string;
        };
        ReadinessResponse: {
            /** @enum {string} */
            status: "ready" | "not_ready";
            /** @constant */
            service: "tool-kit-converter";
            serviceVersion: string;
            checks: {
                /** @enum {string} */
                database: "ok" | "failed";
                /** @enum {string} */
                dataRoot: "ok" | "failed";
                /** @enum {string} */
                worker: "ok" | "failed";
            };
        };
        CapabilitiesEnvelope: {
            data: {
                /** @constant */
                apiVersion: "v1";
                serviceVersion: string;
                conversion: components["schemas"]["ConversionCapabilities"];
                remoteFallback: {
                    /** @constant */
                    provider: "datalab";
                    /** @constant */
                    available: false;
                };
            };
        };
        ConversionCapabilities: {
            acceptingJobs: boolean;
            /** @constant */
            durability: "persistent";
            inputFormats: [
                "application/pdf",
                "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                "application/msword",
                "application/vnd.openxmlformats-officedocument.presentationml.presentation",
                "application/vnd.ms-powerpoint",
                "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                "application/vnd.ms-excel",
                "application/epub+zip",
                "application/vnd.oasis.opendocument.text",
                "application/vnd.oasis.opendocument.spreadsheet",
                "application/vnd.oasis.opendocument.presentation",
                "application/rtf",
                "text/csv",
                "application/vnd.ms-word.document.macroEnabled.12",
                "application/vnd.ms-excel.sheet.macroEnabled.12",
                "application/vnd.ms-powerpoint.presentation.macroEnabled.12",
                "application/vnd.openxmlformats-officedocument.presentationml.slideshow",
                "application/vnd.ms-powerpoint.slideshow.macroEnabled.12"
            ];
            outputFormats: string[];
            profiles: {
                name: components["schemas"]["ConversionProfile"];
                available: boolean;
            }[];
            engines: [
                {
                    /** @constant */
                    name: "pdf-inspector";
                    /** @constant */
                    version: "1.15.0";
                },
                {
                    /** @constant */
                    name: "anydoc";
                    /** @constant */
                    version: "0.1.9";
                }
            ];
            limits: {
                maxUploadBytes: number;
                maxOutputBytes: number;
                maxActiveJobs: number;
                maxConcurrentUploads: number;
            };
        };
        ConversionSubmission: {
            /** Format: binary */
            source: string;
            /** Format: uuid */
            clientRunId: string;
            profile: components["schemas"]["ConversionProfile"];
        };
        /** @enum {string} */
        ConversionProfile: "standard" | "local_only" | "best_quality";
        JobEnvelope: {
            data: components["schemas"]["ConversionJob"];
        };
        ConversionJob: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            activeAttemptId: string;
            /** Format: uuid */
            clientRunId: string;
            profile: components["schemas"]["ConversionProfile"];
            /** @enum {string} */
            status: "queued" | "converting_local" | "finalizing" | "succeeded" | "failed" | "needs_remote";
            route?: {
                /** @constant */
                kind: "local_pdf";
                reasonCodes: string[];
            };
            warnings: string[];
            failure?: {
                code: string;
                message: string;
            };
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ArtifactListEnvelope: {
            data: components["schemas"]["Artifact"][];
        };
        Artifact: {
            /** @enum {string} */
            kind: "markdown" | "manifest";
            /** Format: uuid */
            attemptId: string;
            mediaType: string;
            byteLength: number;
            sha256: components["schemas"]["Sha256"];
            href: string;
        };
        ConversionManifest: {
            /** @constant */
            schemaVersion: 1;
            /** Format: uuid */
            jobId: string;
            /** Format: uuid */
            attemptId: string;
            /** Format: uuid */
            clientRunId: string;
            profile: components["schemas"]["ConversionProfile"];
            source: components["schemas"]["ManifestArtifact"];
            engine: {
                /** @constant */
                name: "pdf-inspector";
                /** @constant */
                version: "1.15.0";
                features: string[];
            };
            route: {
                /** @constant */
                kind: "local_pdf";
                reasonCodes: [
                    "native_text_pdf"
                ];
            };
            document: components["schemas"]["Inspection"];
            warnings: string[];
            output: components["schemas"]["ManifestArtifact"];
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            completedAt: string;
        };
        ManifestArtifact: {
            mediaType: string;
            byteLength: number;
            sha256: components["schemas"]["Sha256"];
        };
        Inspection: {
            /** @constant */
            pdfType: "text_based";
            confidence: number;
            pageCount: number;
            pagesNeedingOcr: number[];
            ocrReasonsByPage: Record<string, never>[];
            /** @constant */
            hasEncodingIssues: false;
            isComplex: boolean;
            pagesWithTables: number[];
            pagesWithColumns: number[];
            processingTimeMs: number;
        };
        Sha256: string;
        ErrorEnvelope: {
            error: {
                code: string;
                message: string;
                /** Format: uuid */
                requestId: string;
                details: Record<string, never>[];
            };
        };
    };
    responses: {
        /** @description Service health */
        Health: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["HealthResponse"];
            };
        };
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Missing or invalid bearer token */
        Unauthorized: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                "WWW-Authenticate"?: "Bearer";
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Upload deadline exceeded */
        RequestTimeout: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Idempotency, profile, or artifact-state conflict */
        Conflict: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Upload exceeded configured byte limits */
        PayloadTooLarge: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Source extension, declared media type, or content signature failed */
        UnsupportedMediaType: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Multipart field semantics are invalid */
        UnprocessableEntity: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Active job capacity reached */
        TooManyRequests: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Conversion, artifact, or route not found */
        NotFound: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Safe internal failure without parser details */
        InternalError: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Malformed request */
        Error400: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        ConversionId: string;
        /** @description Durable per-token record; 1-128 URL-safe characters */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: {
        /** @description Server-generated correlation identifier */
        RequestId: string;
        /** @description Polling URL for the accepted conversion */
        Location: string;
        /** @description Suggested polling delay in seconds */
        RetryAfter: 1;
        /** @description Whether this response reused a stored idempotency record */
        IdempotencyReplayed: boolean;
        /** @description Quoted SHA-256-backed artifact entity tag */
        ArtifactEtag: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getLiveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Health"];
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every dependency check passed */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
            /** @description At least one dependency check failed */
            503: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
    getCapabilities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current service capabilities */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapabilitiesEnvelope"];
                };
            };
        };
    };
    createConversion: {
        parameters: {
            query?: never;
            header: {
                /** @description Durable per-token record; 1-128 URL-safe characters */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["ConversionSubmission"];
            };
        };
        responses: {
            /** @description Upload completed and the conversion was accepted */
            202: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    Location: components["headers"]["Location"];
                    "Retry-After": components["headers"]["RetryAfter"];
                    "Idempotency-Replayed": components["headers"]["IdempotencyReplayed"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            408: components["responses"]["RequestTimeout"];
            409: components["responses"]["Conflict"];
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            422: components["responses"]["UnprocessableEntity"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    getConversion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ConversionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current conversion state */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listConversionArtifacts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ConversionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Empty until publication; two entries after success */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactListEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    downloadConversionMarkdown: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ConversionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Published Markdown */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    ETag: components["headers"]["ArtifactEtag"];
                    [name: string]: unknown;
                };
                content: {
                    "text/markdown": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    downloadConversionManifest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ConversionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Versioned provenance manifest */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    ETag: components["headers"]["ArtifactEtag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversionManifest"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
}
